spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/112f2dfc-b078-4610-b12a-09ab93a6c933/
          jwk-set-uri: https://login.microsoftonline.com/azuregoswami.com/discovery/v2.0/keys?appid=d923d979-d308-4de8-b939-4ce0435521c6
