# Logger Configuration
logging:
  level:
    root: INFO
# embedded server configuration
server:
  port: ${NOMAD_HOST_PORT_http:8091}
  servlet:
    context-path : /VendorAPI

# Resilience4j configuration , Retry, Exponential Backoff, Circuit Breaker, Rate Limiter, Timelimiter, Bulkhead
resilience4j:
  retry:
    instances:
      smsSender:
        maxRetryAttempts: 2
        waitDuration: 2s
        # Exponential backoff strategy
        #enable-exponential-backoff: true
        #exponential-backoff-multiplier: 2
        # Conditional Retry on Exception
        #retry-exceptions:
        #-org.springframework.web.client.RestClientException
        #ignore-exceptions:
        #-com.amrut.prabhu.IgnoreException
  #circuitbreaker:
  #  instances:
  #    myCircuitBreaker:
  #      wait-duration-in-open-state: 1m
  #      permitted-number-of-calls-in-half-open-state: 3
  #      sliding-window-type: count-based
  #      sliding-window-size: 5
  #      minimum-number-of-calls: 5
  #      slow-call-duration-threshold: 10s
  #      slow-call-rate-threshold: 60
  #      failure-rate-threshold: 60
  ratelimiter:
    instances:
      basic_rate_limiter:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 2s

auth:
  audience: api://581c4b1d-c860-48a1-b57f-c4ac499338ef

spring:
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/112f2dfc-b078-4610-b12a-09ab93a6c933/
          jwk-set-uri: https://login.microsoftonline.com/azuregoswami.com/discovery/v2.0/keys?appid=d923d979-d308-4de8-b939-4ce0435521c6
# Set here configurations for the database connection
  datasource:
    url: jdbc:db2://10.3.0.94:50000/PCOMMON
    username: pcuser1
    password: Dev@pcm543
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    validationQuery: SELECT 1

# JPA / HIBERNATE Configuration
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.DB2Dialect
# Naming strategy
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

