name: Spring Boot-application-CI-CD-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: 'goswamiapp001'
  PACKAGE_PATH: './publish'
  DOTNET_VERSION: '3.1.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Code from Repository
      uses: actions/checkout@v2
    
    - name: Setup "Setup Java Environment"
      run: echo "Setup Java Environment"