name: Spring Boot-application-CI-CD-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PACKAGE_PATH: './spring-boot-vendor-rating-api/target/VendorRatingAPI-0.0.1-SNAPSHOT.jar'
  JAVA_VERSION: '8'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Source Code from Repository
      uses: actions/checkout@v2
    
    - name: Setup "Setup Java Environment"
      uses: actions/setup-java@v2
      with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'

    - name: Build with Maven
      run: mvn clean package
    
    - name: Publish Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Spring Boot API-Executable Jar
        path: ${{env.PACKAGE_PATH}}